apiVersion: v1
kind: Service
metadata:
  name: nautilus
  labels:
    app.kubernetes.io/name: nautilus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nautilus
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
